### PR TITLE
fix(remix-react): add missing hash when redirecting client side

### LINKED ISSUE #1641: [Bug]: Cannot add hash to redirect url
### Which Remix packages are impacted?

- `remix` (Remix core)

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.13.0

### Steps to Reproduce

Add a hash to your loader function or action function redirect. It never reaches the url bar.

```typescript
export const loader = () => {
   return redirect('/#hash');
}
```

### Expected Behavior

The hash that is added to the redirect url should take effect in the browser and be accessible via the `useLocation` hook.

### Actual Behavior

The hash never makes it to the browser and cannot be accessed via the `useLocation` hook.

### Note

SearchParams work just fine. It's just the hash that is not working.

### PR DESCRIPTION
**Pull request by machour**
Closes #1641

### CODE REVIEW

File: integration/transition-test.ts [hunk 1]
```diff
@@ -190,6 +202,17 @@ describe("rendering", () => {
     expect(html).toMatch(PAGE_INDEX_TEXT);
   });
 
+  test("loader redirect with hash", async () => {
+    await app.goto("/");
+
+    let responses = app.collectDataResponses();
```
Comment (MichaelDeBoey) [inline integration/transition-test.ts:208]: It seems like the response isn't used, so we could just do the call without assigning it I guess

```suggestion
    app.collectDataResponses();
```

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]
One tiny remark, but awesome first code PR overall! 👊

File: integration/transition-test.ts (hunk 1 above)
Comment (machour) [reply integration/transition-test.ts]: That was a copy/paste leftover, thanks for noticing !
