### PR TITLE
Fix native fetch immutable headers issue

### LINKED ISSUE #9691: Environment variables not working in dev mode when navigating to a different route
### Reproduction

Reproduction: https://github.com/nareshbhatia/remix-nested-layouts

```shell
npm ci
npm run dev
```

1. Point your browser to http://localhost:3000/
2. Click on the `Movies` tab. App navigates to http://localhost:3000/movies. However it crashes with error: `TypeError: immutable`.
3. Refresh the browser without changing the URL. Page refreshes correctly showing a list of movies.

This indicates that the loader is reading the `API_URL` environment variable correctly for full page render, however when navigating from page to page, it can't read the environment variable.

This problem does not exist in production mode. See prod deployment at https://remix-nested-layouts-coral.vercel.app/

### System Info

```shell
System:
    OS: macOS 13.6.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 55.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @remix-run/dev: ^2.10.0 => 2.10.0
    @remix-run/node: ^2.10.0 => 2.10.0
    @remix-run/react: ^2.10.0 => 2.10.0
    @remix-run/serve: ^2.10.0 => 2.10.0
    vite: ^5.3.2 => 5.3.2
```

### Used Package Manager

npm

### Expected Behavior

I should be able to navigate to any page, or click on various movies in the movie list and the app should not crash (in dev mode). The basic issue is that environment variables are not being read when navigating from page to page.

### Actual Behavior

App crashes when navigating from page to page.

### PR DESCRIPTION
**Pull request by brophdawg11**
Fixes #9691

### CODE REVIEW

File: packages/remix-server-runtime/__tests__/server-test.ts [hunk 1]
```diff
@@ -612,6 +612,35 @@ describe("shared server runtime", () => {
...
+    test("data request calls loader returning raw fetch response", async () => {
+      let build = mockServerBuild({
+        root: {
+          default: {},
+        },
+        "routes/_index": {
+          parentId: "root",
+          index: true,
+          loader() {
+            return fetch(`https://remix.run/docs/en/main?_data=root`);
```
Comment (brophdawg11) [inline packages/remix-server-runtime/__tests__/server-test.ts:624]: I don't really want to keep this here but the only way to replicate this issue was to actually get a legit `Response` from a `fetch` call which is why we didn't run into this before.  Thoughts on how to best prevent a regression in this area without spamming our prod server?

File: packages/remix-server-runtime/server.ts [hunk 2]
```diff
@@ -360,12 +360,12 @@ async function handleDataRequest(
 
     // Mark all successful responses with a header so we can identify in-flight
     // network errors that are missing this header
-    response.headers.set("X-Remix-Response", "yes");
```
Comment (brophdawg11) [inline packages/remix-server-runtime/server.ts:363]: If this response is a direct `undici` `fetch` `Response`, then the headers are immutable and we can't change them.  I didn't want to clone the response in 100% of scenarios since this isn't an issue with `return json()` and alternatives, so I am only cloning if this operation throws the `immutable` error

**Comment by myfrontpocket** [comment]
So, I think this is the same issue here: https://github.com/remix-run/remix/issues/9212

I've updated to 2.10.2, and this does restore the previous behavior, with the exception that returning the error response results in a framework exception (that I suppose would be caught by an ErrorBoundary).  Shouldn't this only happen if we `throw` the response rather than `return` it?

```
const response = await fetch('some-url.com')

if (!response.ok) {
  return response; // this acts a throw
}

// continue processing...
```

**Comment by brophdawg11** [comment]
I do not see that behavior.  Please open a ne wissue with a reporduction and we can take a look.  But my quick attempt works as expected:

```jsx
// routes/page.tsx
import { useLoaderData } from "@remix-run/react";

export async function loader() {
  const response = await fetch("http://localhost:5173/resource");

  if (!response.ok) {
    return response;
  }

  return { message: "from loader" };
}

export default function Comp() {
  const data = useLoaderData();
  return <p>data: {data?.message}</p>;
}

// routes/resource.tyx
import { json } from "@remix-run/node";

export function loader() {
  return json({ message: "from resource route" }, { status: 500 });
}
```

**Comment by myfrontpocket** [comment]
> I do not see that behavior. Please open a ne wissue with a reporduction and we can take a look. But my quick attempt works as expected:
> 
> ```js
> // routes/page.tsx
> import { useLoaderData } from "@remix-run/react";
> 
> export async function loader() {
>   const response = await fetch("http://localhost:5173/resource");
> 
>   if (!response.ok) {
>     return response;
>   }
> 
>   return { message: "from loader" };
> }
> 
> export default function Comp() {
>   const data = useLoaderData();
>   return <p>data: {data?.message}</p>;
> }
> 
> // routes/resource.tyx
> import { json } from "@remix-run/node";
> 
> export function loader() {
>   return json({ message: "from resource route" }, { status: 500 });
> }
> ```

Hmmm... is it the same for an action function?  Not sure if it'll make a difference. This is where I'm currently seeing it happen
