### PR TITLE
fix(remix-dev): re-use `REMIX_DEV_SERVER_WS_PORT` when reloading config

### LINKED ISSUE #2958: Remix dev asset server web socket error
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

1.npm i create-remix mydemo
2.remix dev
3.Modify or add files in routes
4.chrome error(Remix dev asset server web socket error:)

image

### Expected Behavior

Automatically refresh the page to match the new route.
To fix this I had to reboot.

### Actual Behavior

image

### PR DESCRIPTION
**Pull request by mcansh**
closes REM-1091

closes #2958

Signed-off-by: Logan McAnsh <logan@mcan.sh>

- [ ] Docs
- [x] Tests

Testing Strategy:

I opened up a new playground (`npm run playground:new`) with a basic node server running on port 8002 and then created a few new files to trigger the config reload while logging the current `REMIX_DEV_SERVER_WS_PORT`.
image

### CODE REVIEW

**Comment by tessellator** [comment]
I think this can still get you in trouble wrt #296. If you set `REMIX_DEV_SERVER_WS_PORT` to the same value in two different projects, you would lose the advantage of using `getPort`. I will test to verify. I provided a similar solution in #3202 that will work in two projects simultaneously.

**Comment by tessellator** [comment]
Confirmed, but on second thought this behavior might be desirable. This PR makes `REMIX_DEV_SERVER_WS_PORT` explicit and will fail fast if the port is already taken, whereas the other PR is a "best effort" and will rewrite `REMIX_DEV_SERVER_WS_PORT` rewritten if the port is already taken.

**Review by jacob-ebey — APPROVED** [review]

File: packages/remix-dev/config.ts [hunk 1]
```diff
@@ -359,6 +359,10 @@ export async function readConfig(
     );
   }
   let devServerPort = await getPort({ port: appConfig.devServerPort });
+  // check if the port is already in use (e.g this file is reloaded after a dep install or config change)
+  if (process.env.REMIX_DEV_SERVER_WS_PORT) {
+    devServerPort = Number(process.env.REMIX_DEV_SERVER_WS_PORT || "8002");
+  }
```
Comment (kentcdodds) [inline packages/remix-dev/config.ts:365]: Doing things this way avoids the unnecessary `getPort` call:

```suggestion
  let devServerPort;
  // check if the port is already in use (e.g this file is reloaded after a dep install or config change)
  if (process.env.REMIX_DEV_SERVER_WS_PORT) {
    devServerPort = Number(process.env.REMIX_DEV_SERVER_WS_PORT || "8002");
  } else {
    devServerPort = await getPort({ port: appConfig.devServerPort })
  }
```

**Review by kentcdodds — CHANGES_REQUESTED** [review]
Thanks! What do you think about this?

File: packages/remix-dev/config.ts (hunk 1 above)
Comment (tessellator) [reply packages/remix-dev/config.ts:365]: Is the `|| "8002"` necessary? `REMIX_DEV_SERVER_WS_PORT` has already been determined to be truthy.

File: packages/remix-dev/config.ts [hunk 2]
```diff
@@ -353,12 +353,19 @@ export async function readConfig(
...
-    appConfig.devServerPort = Number(
-      process.env.REMIX_DEV_SERVER_WS_PORT || 8002
-    );
+  let devServerPort: number;
+
+  // check if the port is already in use as this file is reloaded after a dep install or config change
+  if (process.env.REMIX_DEV_SERVER_WS_PORT) {
+    try {
+      devServerPort = Number(process.env.REMIX_DEV_SERVER_WS_PORT);
+    } catch (error: unknown) {
```
Comment (tessellator) [inline packages/remix-dev/config.ts:362]: I'm unsure if `Number` ever throws an error. In most cases it will return `NaN` instead. 

In this part of the code, it would mean that someone explicitly set the env var to an invalid value. If it wasn't set explicitly, then it would either 1) fall through to `getPort` on the initial load, or 2) have been set to the output of `getPort` on a previous load. 

Is `getPort` as default the right thing to do if someone explicitly sets the env var to an invalid value? (Genuinely curious as to the philosophy of the Remix team.)

Comment (mcansh) [reply packages/remix-dev/config.ts:362]: yup, you're right on the NaN, Mondays amirite 😅. i'll wait for @kentcdodds' thoughts on the default behavior, i could see throwing an error as the desired behavior

Comment (tessellator) [reply packages/remix-dev/config.ts:362]: Awesome. :) Thanks so much for working on this. I'm excited to see LiveReload working again!

File: packages/remix-dev/config.ts [hunk 3]
```diff
@@ -353,12 +353,16 @@ export async function readConfig(
...
-    );
+  let devServerPort: number;
+
+  // check if the port is already in use as this file is reloaded after a dep install or config change
+  if (process.env.REMIX_DEV_SERVER_WS_PORT) {
+    devServerPort =
+      Number(process.env.REMIX_DEV_SERVER_WS_PORT) ||
+      (await getPort({ port: appConfig.devServerPort }));
+  } else {
+    devServerPort = await getPort({ port: appConfig.devServerPort });
```
Comment (kentcdodds) [inline packages/remix-dev/config.ts:364]: How about this:

```suggestion
  let devServerPort = Number(process.env.REMIX_DEV_SERVER_WS_PORT) || await getPort({ port: Number(appConfig.devServerPort) || null });
```

Only thing is it wouldn't work with a port of `0`, but I don't think that's a concern... We can't use `??` because `NaN`.

This also handles the case of `devServerPort` not being configured properly.

**Review by kentcdodds — CHANGES_REQUESTED** [review]
Another thought

**Review by kentcdodds — APPROVED** [review]
Sweet! Thanks 👏👏

File: packages/remix-dev/config.ts [hunk 4]
```diff
@@ -353,12 +353,8 @@ export async function readConfig(
       path.join("public", "build")
   );
 
-  if (typeof appConfig.devServerPort !== "number") {
-    appConfig.devServerPort = Number(
-      process.env.REMIX_DEV_SERVER_WS_PORT || 8002
-    );
+  let devServerPort = Number(process.env.REMIX_DEV_SERVER_WS_PORT) || await getPort({ port: Number(appConfig.devServerPort) || null });
   }
```
Comment (kentcdodds) [inline packages/remix-dev/config.ts:357]:
```suggestion
```

**Review by kentcdodds — APPROVED** [review]
Whoops 😅 Ok, should be good now!

File: packages/remix-dev/config.ts [hunk 5]
```diff
@@ -353,12 +353,7 @@ export async function readConfig(
       path.join("public", "build")
   );
 
-  if (typeof appConfig.devServerPort !== "number") {
-    appConfig.devServerPort = Number(
-      process.env.REMIX_DEV_SERVER_WS_PORT || 8002
-    );
-  }
-  let devServerPort = await getPort({ port: appConfig.devServerPort });
+  let devServerPort = Number(process.env.REMIX_DEV_SERVER_WS_PORT) || await getPort({ port: Number(appConfig.devServerPort) || null });
```
Comment (kentcdodds) [inline packages/remix-dev/config.ts:356]:
```suggestion
  let devServerPort = Number(process.env.REMIX_DEV_SERVER_WS_PORT) || await getPort({ port: Number(appConfig.devServerPort) || undefined });
```

**Review by kentcdodds — APPROVED** [review]
I really shouldn't use our CI as my development environment 😅

**Comment by EkaanshArora** [comment]
Hi team,

This breaks out of the box hot-reload with some of the templates (eg: [just the basics +  express](https://github.com/remix-run/remix/issues/3237)) as the used port is different from the expected `8002` default port for these configurations. (#3237)

This is because the new code gets a random available port if the environment variable isn't set - it's undefined for the templates as `remix.config.js` does not include a `devServerPort`.

Should the templates be updated to have `"devServerPort": 8002` in the `remix.config.js`?

**Comment by kentcdodds** [comment]
@EkaanshArora, thanks. @mcansh is going to look into this.

**Comment by danditomaso** [comment]
Any updates on this issue?
