### PR TITLE
Fix `dest already exists` build errors

### LINKED ISSUE #9498: Build fails when using vite-imagetools plugin due to assets already existing in build/client
I get the following error when building Remix. 

```
Error: [remix] dest already exists.
    at /Users/xxx/site/node_modules/fs-extra/lib/move/move.js:51:31
    at /Users/xxx/site/node_modules/universalify/index.js:22:54 {
  code: 'PLUGIN_ERROR',
  plugin: 'remix',
  hook: 'writeBundle'
}
ERROR: "build-remix" exited with 1.
```

It seems that there is a build step where `build/server/assets` are moved over to `build/client/assets`, but the images already exist there and the build fails due to the way `fs-extra/lib/move/move.js` behaves.

```
// fs-extra/lib/move/move.js
function doRename (src, dest, overwrite, isChangingCase, cb) {
  if (isChangingCase) return rename(src, dest, overwrite, cb)
  if (overwrite) {
    return remove(dest, err => {
      if (err) return cb(err)
      return rename(src, dest, overwrite, cb)
    })
  }
  pathExists(dest, (err, destExists) => {
    if (err) return cb(err)
    if (destExists) return cb(new Error('dest already exists.')) // the cause of the error
    return rename(src, dest, overwrite, cb)
  })
}
```

I am using `vite-imagetools` which causes the assets to already exist in `build/client/assets`.

When calling directly `vite build` everything works. So to me it seems that Remix should do a better job at moving the files from `build/server/assets` to `build/client/assets` and not fail.

### PR DESCRIPTION
**Pull request by markdalgleish**
Fixes #9498.

This fix was inspired by #9800, but I decided to make this more error-proof by inspecting files on disk rather than inspecting the Vite manifest files/assets and potentially getting it wrong (as we have already).

### CODE REVIEW

File: packages/remix-dev/vite/plugin.ts [hunk 1]
```diff
@@ -1419,8 +1411,9 @@ export const remixVitePlugin: RemixVitePlugin = (remixUserConfig = {}) => {
           let movedAssetPaths: string[] = [];
           for (let ssrAssetPath of ssrAssetPaths) {
             let src = path.join(serverBuildDirectory, ssrAssetPath);
-            if (!clientFilePaths.has(ssrAssetPath)) {
-              let dest = path.join(clientBuildDirectory, ssrAssetPath);
+            let dest = path.join(clientBuildDirectory, ssrAssetPath);
+
+            if (!fse.existsSync(dest)) {
```
Comment (markdalgleish) [inline packages/remix-dev/vite/plugin.ts:1416]: Since (assuming no errors) we were guaranteed to either move the SSR asset or delete it depending on whether it's present in the client assets, it's much safer to use the file system as the source of truth rather than trying to infer what's on disk based on the Vite manifest.
