### PR TITLE
Fix root default HydrateFallback when Layout exists

### LINKED ISSUE #8880: SPA Mode: get invalid HTML when `HydrateFallback` is omitted (using `Layout`)
### Reproduction

1. Create a new Remix app with SPA template `npx create-remix@latest --template remix-run/remix/templates/spa`
2. Remove `HydrateFallback` export

### System Info

```shell
Not related
```

### Used Package Manager

npm

### Expected Behavior

The index HTML is correctly generated with `Layout` content without children

### Actual Behavior

The internal default `HydrateFallback` full HTML is rendered inside `Layout`, generating invalid HTML.

### PR DESCRIPTION
**Pull request by brophdawg11**
Same as #8859 but for the default root `HydrateFallback`

Closes #8880

### CODE REVIEW

File: packages/remix-react/errorBoundaries.tsx [hunk 1]
```diff
@@ -69,11 +69,9 @@ export function RemixRootDefaultErrorBoundary({ error }: { error: unknown }) {
   if (isRouteErrorResponse(error)) {
     return (
       <BoundaryShell title="Unhandled Thrown Response!">
-        <main style={{ fontFamily: "system-ui, sans-serif", padding: "2rem" }}>
-          <h1 style={{ fontSize: "24px" }}>
-            {error.status} {error.statusText}
-          </h1>
-        </main>
```
Comment (brophdawg11) [inline packages/remix-react/errorBoundaries.tsx:76]: Moved the `main` element into `BoundaryShell` so it's consistent across all default root component implementations
