### PR TITLE
fix(dev): serve any non-Remix assets from `public/`

### LINKED ISSUE #6271: Remix 1.16 `unstable_dev` - problems with assets
### What version of Remix are you using?

1.16

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `git clone git@github.com:ArekBartnik/remix-116-dev-assets.git`
2. `npm i`
3. `npm run dev`
4. go to `http://localhost:3000`

### Expected Behavior

It should show a page using Inter font and an icon after "Welcome to Remix".

| With `unstable_dev: true;` | Without `unstable_dev: true`|
|-|-|
|image| image|

Without new devserver paths to assets are relative but after turning this flag they change to absolute.

### Actual Behavior

There're 2 errors:
- for the fonts -> 404 `http://localhost:3001/fonts/InterV.var.woff2 net::ERR_ABORTED 404 (Not Found)`
- for the svg icon -> `Unsafe attempt to load URL http://localhost:3001/build/_assets/document-QP6N4QKU.svg from frame with URL http://localhost:3000/. Domains, protocols and ports must match.

image

### PR DESCRIPTION
**Pull request by pcattori**
Fixes #6271

### CODE REVIEW

File: packages/remix-dev/devServer_unstable/index.ts [hunk 1]
```diff
@@ -196,6 +196,7 @@ export let serve = async (
         maxAge: "1y",
       })
     )
+    .use("*", express.static("public", { maxAge: "1h" }))
```
Comment (kentcdodds) [inline packages/remix-dev/devServer_unstable/index.ts:199]: I believe the public directory is configurable right? Maybe this should be dynamic based on the config?

Comment (pcattori) [reply packages/remix-dev/devServer_unstable/index.ts:199]: the Remix assets build directory (e.g. `public/build/`) is configurable, but I don't think we have config for `public/` itself.

Comment (pcattori) [reply packages/remix-dev/devServer_unstable/index.ts]: Ok we can make this configurable for dev. Shouldn't need to be set in prod since you already have control of your app server, but in dev we need to make sure we play nicely with any setup.

Comment (pcattori) [reply packages/remix-dev/devServer_unstable/index.ts]: `--public-directory` / `unstable_dev.publicDirectory` option added!

**Review by jacob-ebey — APPROVED** [review]
