### PR TITLE
fix(remix-architect,remix-node): don't parse multipart `formData` to string

### LINKED ISSUE #2476: Architect multipart forms with file uploads result in corrupted files
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

 - Create a new remix project with `npx create-remix`
 - Select "Just the basics"
 - Select "Architect (AWS Lambda)"
 - Select "Typescript"
 - Finish creating the project
 - Replace the contents of `app/routes/index.tsx` with the following code:

```typescript
import {
  ActionFunction,
  Form,
  unstable_createFileUploadHandler,
  unstable_parseMultipartFormData,
} from "remix";

export const action: ActionFunction = async ({ request }) => {
  const uploadHandler = unstable_createFileUploadHandler({
    maxFileSize: 10_000_000,
    directory: "public/uploads",
    file: ({ filename }) => filename,
  });

  const formData = await unstable_parseMultipartFormData(
    request,
    uploadHandler
  );

  const file = formData.get("file-upload") as File;

  if (file) {
    console.log(`File uploaded to server/public/uploads/${file.name}`);
  } else {
    console.log("No file uploaded");
  }

  return {};
};

export default function Index() {
  return (
    <Form reloadDocument method="post" encType="multipart/form-data">
      <div>
        <label htmlFor="file-upload">
          <span>Upload a file</span>
          <input
            id="file-upload"
            name="file-upload"
            type="file"
          />
        </label>

        <button type="submit">Upload image</button>
      </div>
    </Form>
  );
}
```

- Run the server locally with `npm run dev`
- Open `http://localhost:3333` in your web browser and choose an image file to upload
- Submit the form
- View the file in `<root>/server/public/uploads`

### Expected Behavior

The file should be uploaded uncorrupted

### Actual Behavior

The file that is uploaded isn't the same file as the one selected, has additional data that is "corrupting" the file

### PR DESCRIPTION
**Pull request by hicksy**
A fix to resolve #2476

File uploads using Architect were producing corrupted files. I noted that the byte size was larger than expected on the corrupted file, and confirmed the same was true when using `unstable_createMemoryUploadHandler`. 

If i manually parsed the event body within a modified `createRemixRequest` in /server/node_modules/@remix-run/architect/server.js` I was able to obtain the correct byte length. 

(Documented my initial tests in issue[ #2476](https://github.com/remix-run/remix/issues/2476))

Further investigation, I've found that using `toString()` on the Buffer within `createRemixRequest` and `toString()` on the body when creating the Readable within `parseMultipartFormData` was modifying the buffer (presumably something to do with converting it to utf-8?)

I've modified `createRemixRequest` to do the following:

1. Determine if the event is a formData request (checking for content-type multipart/form-data)
2. if not, handle the base64 event in the current way
3. if it is a formData request, pass the Buffer as event.body rather than converting it to string. 

I've modified `parseMultipartFormData` by removing `toString` from body when creating the Readable. It'll eiether already be a string, or a Buffer

Closes: #2476

- [*] Tests

### CODE REVIEW

File: packages/remix-architect/server.ts [hunk 1]
```diff
@@ -69,13 +69,21 @@ export function createRemixRequest(
...
   let search = event.rawQueryString.length ? `?${event.rawQueryString}` : "";
   let url = new URL(event.rawPath + search, `https://${host}`);
-
+  let isFormData = false;
+  if (
+    event.headers["content-type"] &&
+    event.headers["content-type"].includes("multipart/form-data")
+  ) {
+    isFormData = true;
+  }
```
Comment (MichaelDeBoey) [inline packages/remix-architect/server.ts:78]: This can be simplified to

```suggestion
  let isFormData = event.headers["content-type"]?.includes("multipart/form-data");
```

File: packages/remix-architect/server.ts [hunk 2]
```diff
@@ -69,13 +69,21 @@ export function createRemixRequest(
...
   return new NodeRequest(url.href, {
     method: event.requestContext.http.method,
     headers: createRemixHeaders(event.headers, event.cookies),
     body:
       event.body && event.isBase64Encoded
-        ? Buffer.from(event.body, "base64").toString()
+        ? !isFormData
+          ? Buffer.from(event.body, "base64").toString()
+          : Buffer.from(event.body, "base64")
```
Comment (MichaelDeBoey) [inline packages/remix-architect/server.ts:86]: Making the condition positive, will create a lower cognitive load.

```suggestion
        ? isFormData
          ? Buffer.from(event.body, "base64")
          : Buffer.from(event.body, "base64").toString()
```

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]

File: packages/remix-architect/server.ts (hunk 1 above)
Comment (hicksy) [reply packages/remix-architect/server.ts]: Ah yes, of course. I had it that way originally and then switched it out to the longer form to produce an easier to follow example .js file for the issue. 

Much better like this, thanks

File: packages/remix-architect/server.ts (hunk 2 above)
Comment (hicksy) [reply packages/remix-architect/server.ts]: Yes, much easier to read, thanks

**Review by hicksy — COMMENTED** [review]
Thanks for the feedback. All good

**Comment by hicksy** [comment]
@MichaelDeBoey do I have any more actions to take on this?

**Review by MichaelDeBoey — APPROVED** [review]
