### PR TITLE
Read Vite config in `reveal`/`routes` commands

### LINKED ISSUE #8845: remix routes does not work with vite
### Reproduction

Make a vite-based remix app with a custom route config

### System Info

```shell
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 9.93 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/n/bin/node
    Yarn: 1.22.17 - ~/n/bin/yarn
    npm: 10.2.3 - ~/n/bin/npm
    pnpm: 7.25.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 121.1.62.165
    Chrome: 121.0.6167.184
    Safari: 17.2.1
  npmPackages:
    @remix-run/css-bundle: 2.7.2 => 2.7.2 
    @remix-run/dev: 2.7.2 => 2.7.2 
    @remix-run/eslint-config: 2.7.2 => 2.7.2 
    @remix-run/express: 2.7.2 => 2.7.2 
    @remix-run/node: 2.7.2 => 2.7.2 
    @remix-run/react: 2.7.2 => 2.7.2 
    @remix-run/serve: 2.7.2 => 2.7.2 
    @remix-run/server-runtime: 2.7.2 => 2.7.2 
    @remix-run/testing: 2.7.2 => 2.7.2 
    vite: ^5.1.4 => 5.1.4
```

### Used Package Manager

npm

### Expected Behavior

I expect `remix routes` to show my routes

### Actual Behavior

It does not show my routes

### LINKED ISSUE #8881: SPA Mode: `remix reveal` generate entries files with unexpected content
### Reproduction

1. Create a new Remix app with SPA template `npx create-remix@latest --template remix-run/remix/templates/spa`
2. Delete `entry.server.tsx` and `entry.client.tsx` files
3. Run `remix reveal`

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.71 GB / 15.73 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @remix-run/dev: ^2.7.2 => 2.7.2
    @remix-run/node: ^2.7.2 => 2.7.2
    @remix-run/react: ^2.7.2 => 2.7.2
    vite: ^5.1.0 => 5.1.4
```

### Used Package Manager

npm

### Expected Behavior

Since `ssr` is set to `false` in `vite.config.ts`, I would expect `entry.server.tsx` to contain the code that generates a static index.html file.

### Actual Behavior

An `entry.server.tsx` for SSR is generated.

### PR DESCRIPTION
**Pull request by markdalgleish**
Fixes #8845
Fixes #8881

### CODE REVIEW

File: packages/remix-dev/vite/build.ts [hunk 1]
```diff
@@ -8,53 +8,15 @@ import {
...
-    | undefined;
-
-  if (!ctx) {
-    console.error(colors.red("Remix Vite plugin not found in Vite config"));
-    process.exit(1);
-  }
-
-  return ctx;
-}
-
```
Comment (markdalgleish) [inline packages/remix-dev/vite/build.ts:57]: This has moved to `vite/plugin.ts` since the logic is now shared and not specific to the `vite:build` command.

File: packages/remix-dev/vite/build.ts [hunk 2]
```diff
@@ -284,7 +246,15 @@ export async function build(
...
   let viteConfig = await resolveViteConfig({ configFile, mode, root });
-  let ctx = await extractRemixPluginContext(viteConfig);
+
+  // eslint-disable-next-line prefer-let/prefer-let -- Improve type narrowing
+  const ctx = await extractRemixPluginContext(viteConfig);
+
+  if (!ctx) {
+    console.error(colors.red("Remix Vite plugin not found in Vite config"));
+    process.exit(1);
+  }
```
Comment (markdalgleish) [inline packages/remix-dev/vite/build.ts:256]: This error used to be in `extractRemixPluginContext` but since it's now used in contexts where it's not guaranteed that the consumer is using Vite, `extractRemixPluginContext` now returns `undefined` if Vite and/or the Remix Vite plugin aren't found, so we handle the error here now instead.

File: packages/remix-dev/vite/plugin.ts [hunk 3]
```diff
@@ -39,6 +40,70 @@ import { resolveFileUrl } from "./resolve-file-url";
...
+  return viteConfig;
+}
+
+export async function extractRemixPluginContext(
+  viteConfig: Vite.ResolvedConfig
+) {
+  return viteConfig["__remixPluginContext" as keyof typeof viteConfig] as
+    | RemixPluginContext
+    | undefined;
+}
```
Comment (markdalgleish) [inline packages/remix-dev/vite/plugin.ts:74]: As noted above, these have moved from `vite/build.ts`.

File: packages/remix-dev/vite/plugin.ts [hunk 4]
```diff
@@ -39,6 +40,70 @@ import { resolveFileUrl } from "./resolve-file-url";
...
+    ]);
+
+  // V3 TODO: Vite config should not be optional
+  if (!configFile) {
+    return;
+  }
+
+  let viteConfig = await resolveViteConfig({ configFile, root });
+  return await extractRemixPluginContext(viteConfig);
+}
```
Comment (markdalgleish) [inline packages/remix-dev/vite/plugin.ts:105]: This is the logic used by the `reveal` and `routes` commands. Since it's not guaranteed that consumers are using Vite, this function returns `undefined` if a Vite config doesn't exist or if the Remix Vite plugin isn't present.

**Review by brophdawg11 — APPROVED** [review]
Nice work!  Gave it a quick test on my vite app and `npx remix routes` picked up custom routes.  I also pushed a commit to this branch for `npx remix reveal` to reveal the simpler SPA mode server entry.

File: packages/remix-dev/cli/commands.ts [hunk 5]
```diff
@@ -82,13 +83,25 @@ export function setup() {
...
+    configFile: flags.config,
+  });
+
+  let routes =
+    ctx?.remixConfig.routes ||
+    // v3 TODO: Remove this and require the presence of a Vite config
+    (await readConfig(remixRoot)).routes;
 
+  let formatArg = flags.json ? "json" : "jsx";
   let format = isRoutesFormat(formatArg) ? formatArg : RoutesFormat.jsx;
```
[the remark this answers is not in the document]
Comment (brophdawg11) [reply packages/remix-dev/cli/commands.ts]: 402cd6e0a589d783b5f258e8afc66eaa9a7da2ed

File: packages/remix-dev/cli/run.ts [hunk 6]
```diff
@@ -120,14 +120,25 @@ export async function run(argv: string[] = process.argv.slice(2)) {
...
+      argv[0] === "routes"
+        ? // Handle commands that support Vite's --config flag
+          {
+            "--config": String,
+            "-c": "--config",
+          }
+        : {
+            // Handle non Vite config commands
+            "-c": "--command",
+          }),
```
[the remark this answers is not in the document]
Comment (markdalgleish) [reply packages/remix-dev/cli/run.ts:134]: The issue was that `remix vite:` commands are designed to mirror the Vite CLI where `-c` is short for `--config`. This config flag now needs to work with `reveal` and `routes` too. Passing `-c` to these commands currently has no effect.

File: packages/remix-dev/cli/run.ts [hunk 7]
```diff
@@ -120,14 +120,25 @@ export async function run(argv: string[] = process.argv.slice(2)) {
       "--tls-key": String,
       "--tls-cert": String,
 
+      ...(argv[0].startsWith("vite:") ||
```
[the remark this answers is not in the document]
Comment (markdalgleish) [reply packages/remix-dev/cli/run.ts:123]: Updated the `--help` output here: https://github.com/remix-run/remix/pull/8939
