### PR TITLE
fix(remix-react): fix `content-type` on proxied action request

### LINKED ISSUE #4967: `request.text()` fails to produce parseable contents in 1.10-pre5
### What version of Remix are you using?

1.10-pre5

### Steps to Reproduce

This results in  https://remix.run/docs/en/v1/pages/faq#how-can-i-have-structured-data-in-a-form being an invalid approach.

```ts
export const action: ActionFunction = async ({
  request,
  context,
  params,
}): Promise<ActionData | null> => { 
let formQueryString = await request.text();
  console.log({ formQueryString }); 
}
```
  will produce something to this effect: 
```js
{
  formQueryString: '------WebKitFormBoundaryccYLQ3im9udgCOSx\r\n' +
    'Content-Disposition: form-data; name="__rvfInternalFormId"\r\n' +
    '\r\n' +
    'survey_page_step\r\n' +
    '------WebKitFormBoundaryccYLQ3im9udgCOSx\r\n' +
    'Content-Disposition: form-data; name="CLIENT_ID"\r\n' +
    '\r\n' +
    'f68376f2931b4257838ba71f8df8b294\r\n' +
    '------WebKitFormBoundaryccYLQ3im9udgCOSx\r\n' +
    'Content-Disposition: form-data; name="survey.9b33f8ef-f905-49ad-bcd8-50248b61bf6a"\r\n' +
    '\r\n' +
    'Yes\r\n' +
...
}
```

### Expected Behavior

in 1.9.0 it would produce: 

{
  formQueryString: '__rvfInternalFormId=survey_page_step&CLIENT_ID=70843d75c0f34dbba27b2bc32d47b1d9&survey.9b33f8ef-f905-49ad-bcd8-50248b61bf6a=Yes&survey.6f4a11a9-f336-4d26-bf0c-d915aa7583db=No&survey.5512beac-3baa-438e-9218-d3b932df6bbb=Yes&survey.d8ea2fa5-8c8d-4459-9a5a-45036a78ac78=No&survey.ff990415-3ce7-4458-b152-658fad56937c=Yes&survey.ed45ad72-50cc-4598-9124-df906352fff0=No&survey.4891eee5-c333-4ce4-8e8f-310efc93ad8b=Yes'
}

### Actual Behavior

In 1.10-pre5 produces:

```js
{
  formQueryString: '------WebKitFormBoundaryccYLQ3im9udgCOSx\r\n' +
    'Content-Disposition: form-data; name="__rvfInternalFormId"\r\n' +
    '\r\n' +
    'survey_page_step\r\n' +
    '------WebKitFormBoundaryccYLQ3im9udgCOSx\r\n' +
    'Content-Disposition: form-data; name="CLIENT_ID"\r\n' +
    '\r\n' +
    'f68376f2931b4257838ba71f8df8b294\r\n' +
    '------WebKitFormBoundaryccYLQ3im9udgCOSx\r\n' +
    'Content-Disposition: form-data; name="survey.9b33f8ef-f905-49ad-bcd8-50248b61bf6a"\r\n' +
    '\r\n' +
    'Yes\r\n' +
...
}
```

### PR DESCRIPTION
**Pull request by brophdawg11**
Closes #4967

### CODE REVIEW

File: packages/remix-react/data.ts [hunk 1]
```diff
@@ -36,16 +36,18 @@ export async function fetchData(
   let url = new URL(request.url);
   url.searchParams.set("_data", routeId);
 
-  let init: RequestInit | undefined;
+  let init: RequestInit = { signal: request.signal };
```
Comment (brophdawg11) [inline packages/remix-react/data.ts:39]: We can always start with the signal now

File: packages/remix-react/data.ts [hunk 2]
```diff
@@ -36,16 +36,18 @@ export async function fetchData(
...
-    init = { signal: request.signal };
+    init.method = request.method;
+
+    let contentType = request.headers.get("Content-Type");
+    init.body =
+      // Check between word boundaries instead of startsWith() due to the last
+      // paragraph of https://httpwg.org/specs/rfc9110.html#field.content-type
+      contentType && /\bapplication\/x-www-form-urlencoded\b/.test(contentType)
+        ? new URLSearchParams(await request.text())
+        : await request.formData();
```
Comment (brophdawg11) [inline packages/remix-react/data.ts:50]: Conditionally set `URLSearchParams` or `FormData` as the body and let `Content-Type` inherit automatically

**Review by mcansh — APPROVED** [review]

**Review by jacob-ebey — APPROVED** [review]

**Review by MichaelDeBoey — APPROVED** [review]
